apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway

    spec:
      containers:
        - name: api-gateway
          image: week33-api-gateway:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3000

          env:
            - name: USER_SERVICE_URL
              value: http://user-service:3001

            - name: ORDER_SERVICE_URL
              value: http://order-service:3002

            - name: JWT_ACCESS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_ACCESS